### ISSUE TITLE
ขอ support web ด้วยนะขอรับท่านอาจารย์

### ISSUE THREAD

**Issue by MisterKon** [chartchuo/dart-nats#15]
กำลังทดสอบ web อยู่เลยครับ
ขอขอบพระคุณล่วงหน้าเป็นอย่างสูงครับ

**Comment by chartchuo** [comment]
ขอโทษที่ตอบช้านะครับ ไม่ได้เข้ามาดู repo นี้นาน เดิมทำเพื่อ prove of concept ได้เวลาขุด project นี้ขึ้นมาทำต่อ feature แรกที่จะทำก็คือ web support เพราะตัวเองก็จะใช้เหมือนกันครับ
