### ISSUE TITLE
Connect to invalid ws connection does not give error

### ISSUE THREAD

**Issue by battbot-snappy** [chartchuo/dart-nats#16]
When there are errors encountered when connecting to a ws address. The connect goes through successfully and there's no way to hook a handler for when the code into the onError section in the connect implementation below:

try {
          _channel = WebSocketChannel.connect(uri);
          status = Status.connected;
          _connectCompleter.complete();

          _addConnectOption(_connectOption);
          _backendSubscriptAll();
          _flushPubBuffer();

          _buffer = [];
          _channel!.stream.listen((d) {
            // _socket!.listen((d) {
            _buffer.addAll(d);
            while (
                _receiveState == _ReceiveState.idle && _buffer.contains(13)) {
              _processOp();
            }
          }, onDone: () {
            status = Status.disconnected;
            _channel!.sink.close();
            // _socket!.close();
          }, onError: (err) {
            status = Status.disconnected;
            _channel!.sink.close();
            // _socket!.close();
          });
          return;
        } catch (err) {
          close();
          _connectCompleter.completeError(err);
        }
        
        Can be easily reproduced using the example code
    natsClient = nats.Client();
    natsClient.connect(Uri.parse('ws://localhost:1234');
    fooSub = natsClient.sub('foo');
    barSub = natsClient.sub('bar');

You don't get an error even though 1234 is an invalid port and it goes all the way past the sub without getting any indication that something has gone wrong

**Comment by Nevermind-s** [comment]
Any updated on that?

**Comment by chartchuo** [comment]
Sory for late reply, I not visit this repo for long time, and thank you for issue report. 
I will repoduce and fix this.

**Comment by chartchuo** [comment]
fixed in version 0.4.6 
      try {
        await client.connect(Uri.parse('ws://localhost:1234'), retry: false);
      } on NatsException {
        // handle error
      }
