### ISSUE TITLE
Error: from nats-server "websocket handshake error: invalid value for header 'Upgrade' "

### ISSUE THREAD

**Issue by chartchuo** [chartchuo/dart-nats#18]

**Comment by blurredpixel** [comment]
@chartchuo How did you fix this BTW?

**Comment by mbrekhov** [comment]
In my case it was an AWS balancer that executes http healthcheck on port 8089  ¯\_(ツ)_/¯

**Comment by jmndao** [comment]
Hello @mbrekhov , did you fix it ?

**Comment by mbrekhov** [comment]
> Hello @mbrekhov , did you fix it ?

I just ignore these messages 😐

**Comment by jmndao** [comment]
> I just ignore these messages 😐

I see, but in my case, it seems to cause some issues on prod. It seems its preventing some events to flow and my web client is missing on some of them
