### ISSUE TITLE
Jetstream

### ISSUE THREAD

**Issue by DavidWhit** [chartchuo/dart-nats#19]
While reading the documents it says that Jetstream is built in yet I don't see any mechanic that other libs have IE jetstream() jetstreamManager(). Did I miss something?

**Comment by chartchuo** [comment]
Sory for late reply. Jetstream not in plan yet.

**Comment by denzil-mobile-guardian** [comment]
@chartchuo Is there any plan to add JetStream yet?

**Comment by rlch** [comment]
+1

**Comment by MichalNemec** [comment]
Some time has passed—are there any plans to implement JetStream support? Currently, there isn’t any Dart library that supports JetStream, and this library seems to be the most advanced option available. It would be a shame if development stalled at this stage.
