### ISSUE TITLE
larger MSG payloads not always working, check if full payload present in buffer

### ISSUE THREAD

**Issue by aktxyz** [chartchuo/dart-nats#20]
I was having problems with subscription messages with larger payloads (like 20000 bytes) not working properly.
It looks like the code assumes that if a CR is present in the buffer, then there is a full protocol message in the buffer ... but for larger payloads on the MSG type message, the full payload can take longer to arrive.  

I am using the code below to get around this, seems to work ok.  Basically it does a check to see if the buffer contains a MSG, and if so plucks out the length of the message, then checks to see if the buffer contains the whole payload ... and only calls the processOp() if the payload is complete ... otherwise it breaks out of the while() loop

https://github.com/chartchuo/dart-nats/blob/3bfd99244614110803d62fe38fdd1bdf33537fae/lib/src/client.dart#L118

```
            while (_receiveState == _ReceiveState.idle && _buffer.contains(13)) {

              var n13 = _buffer.indexOf(13);
              var msgFull = String.fromCharCodes(_buffer.take(n13)).toLowerCase().trim();
              var msgList = msgFull.split(' ');
              var msgType = msgList[0];
              //print('... process $msgType ${_buffer.length}');

              if (msgType == 'msg') {
                var len = int.parse((msgList.length == 4 ? msgList[3] : msgList[4]));
                if (len > 0 && _buffer.length < (msgFull.length + len + 4)) {
                  break; // not a full payload, go around again
                }
              }

              _processOp();
            }
```

for a larger MSG payload, the commented out print statement produces ...

```
... process msg 17
... process msg 4113
... process msg 8209
... process msg 12305
... process msg 16401
... process msg 20497
... process msg 21079
```

**Comment by chartchuo** [comment]
sory for late reply. and thank for issue report. I will try to repoduce and fix this.

**Comment by chartchuo** [comment]
Thank for you help. I put your code in. and will update in release 0.4.3
