### ISSUE TITLE
[Bug] Unsupported operation: Platform._version

### ISSUE THREAD

**Issue by ngoluuduythai** [chartchuo/dart-nats#21]
I have an error Unsupported operation: Platform._version, when connecting to `wss://{domain}:{port}` with my **Chrome** browser. 

I try WebSocket change to 
```
import 'package:web_socket_channel/web_socket_channel.dart';
 WebSocketChannel.connect(uri);

```
The connection will be connected.

WebSocket from 'dart:html' also works well for the web.

**Comment by chartchuo** [comment]
Thank for your contribution.
