### ISSUE TITLE
snapshot.data sub Message only final msg 

### ISSUE THREAD

**Issue by MisterKon** [chartchuo/dart-nats#4]
สวัสดีครับ ผมตามมาจาก youtube ละครับ 
ผมลอง v 0.1.6 แล้วผล คือ client สามารับ sub message ได้ครบถ้วนจนถึง massage สุดท้ายเรียบร้อย ไม่ delay แล้ว แต่ผมยังเจอปัญหาอยู่เมื่อ client ได้รับ sub message ติดๆกันหรือพร้อมๆกัน เมื่อ log ดู ใน file client.dart สามารถรับ op case 'msg' ได้ครบถ้วนทุก event และเข้า _processMsg() ทุก event แต่เวลาที่จะส่ง payload เข้า _subs[sid].add (Message... มันเหมือน save ทับ message กันครับ ส่งผลให้ได้ msg เพียงอันสุดท้ายที่ส่งต่อไป snapshot.data 

ผมคิดว่าน่าจะแปลง <nats.Message> เป็น list ของ messages น่าจะแก้ปัญหานี้ได้ แล้วเมื่อเวลาจะใช้ snapshot.data ผมก็จะใช้ท่า forEach((data) {}) เอาแต่ละ message ไปใช้งานได้

แต่...ผมไม่มีความสามารถแก้ไขได้สำเร็จ คงต้องรบกวนท่านอีกครั้งแล้วหล่ะครับ ><"

**Comment by chartchuo** [comment]
โอ้ว add ข้อมูลผิด อันนี้เรื่องใหญ่ จะรีบแก้นะครับ

**Comment by chartchuo** [comment]
ปัญหาน่าจะมาจาก StreamBuilder ไม่เรียก builder function ถี่ ๆ ผมลองทำตัวอย่างมาให้ดู

1. sub foo ใช้ stream builder จาก subscription โดยตรง มาเฉพาะ message สุดท้าย
2. sub bar ทำการ listen จาก subscription แล้วโยนต่อไป stream builder ผลคือ รับมาได้ทั้งหมด แต่ stream builder เรียก builder ด้วย message สุดท้ายครั้งเดียว
3. ไม่ใช้ nats client โดยการ add เข้า _noNatsStreamCtrl โดยตรง ผลคือได้อันสุดท้ายอันเดียวเช่นกันครับ

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:dart_nats/dart_nats.dart' as nats;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _editCtrl = TextEditingController();
  nats.Client natsClient;
  nats.Subscription fooSub, barSub;
  final _barStreamCtrl = StreamController<nats.Message>();
  final _noNatsStreamCtrl = StreamController<String>();

  void initState() {
    super.initState();
    connect();
  }

  void connect() {
    natsClient = nats.Client();
    natsClient.connect('10.0.2.2');
    fooSub = natsClient.sub('foo');
    barSub = natsClient.sub('bar');
    barSub.stream.listen((msg) {
      print('listen: ' + msg.string);
      _barStreamCtrl.add(msg);
    });
  }

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Form(
            child: TextFormField(
              controller: _editCtrl,
              decoration: InputDecoration(labelText: 'publish'),
            ),
          ),
          Text('foo message:'),
          StreamBuilder(
            stream: fooSub.stream,
            builder: (context, AsyncSnapshot<nats.Message> snapshot) {
              if (snapshot.hasData) {
                print('snapshot.data: ' + snapshot.data.string);
              }
              return Text(snapshot.hasData ? '${snapshot.data.string}' : '');
            },
          ),
          Text('bar message:'),
          StreamBuilder(
            stream: _barStreamCtrl.stream,
            builder: (context, AsyncSnapshot<nats.Message> snapshot) {
              if (snapshot.hasData) {
                print('snapshot.data: ' + snapshot.data.string);
              }
              return Text(snapshot.hasData ? '${snapshot.data.string}' : '');
            },
          ),
          Row(
            children: <Widget>[
              RaisedButton(
                  child: Text('pub to foo'),
                  onPressed: () => _publishMessage('foo')),
              RaisedButton(
                  child: Text('pub to bar'),
                  onPressed: () => _publishMessage('bar')),
            ],
          ),
          RaisedButton(
            child: Text('pump data to foo'),
            onPressed: () {
              for (var i = 0; i < 100; i++) {
                print('add: $i');
                natsClient.pubString('foo', '$i');
              }
            },
          ),
          RaisedButton(
            child: Text('pump data to bar'),
            onPressed: () {
              for (var i = 0; i < 100; i++) {
                print('add: $i');
                natsClient.pubString('bar', '$i');
              }
            },
          ),
          Text('StreamBuilder:'),
          StreamBuilder(
            stream: _noNatsStreamCtrl.stream,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                print('snapshot.data: ' + snapshot.data);
              }
              return Text(snapshot.hasData ? snapshot.data : '');
            },
          ),
          RaisedButton(
            child: Text('pump data to stream'),
            onPressed: () {
              for (var i = 0; i < 100; i++) {
                print('add: $i');
                _noNatsStreamCtrl.add('$i');
              }
            },
          ),
        ],
      ),
    );
  }

  void _publishMessage(String subject) {
    if (_editCtrl.text.isNotEmpty) {
      natsClient.pubString(subject, _editCtrl.text);
    }
  }

  void dispose() {
    natsClient.close();
    super.dispose();
  }
}

**Comment by MisterKon** [comment]
ยอดเยี่ยมเลยครับ เป็นปัญหาที่ builder func ของ StreamBuilder จริงๆด้วยครับ คงต้องรอให้ทีม flutter ช่วยแก้ไข เพราะคงใช้งานได้เฉพาะกรณี  stream ข้อมูลเดียวกันที่ต้องการใช้ข้อมูลล่าสุดเท่านั้น เคสผมทำระบบ chat มันจำเป็นต้องใช้ข้อมูลทุก msg จึง do something จาก snaptshot.data ไม่ได้ 

ต้องขอขอบคุณท่านอาจารย์ Chart  สำหรับคำแนะนำท่าที่สามารถจัดการ ได้ครบทุก msg ตามตัวอย่างข้อ 2 ซึ่งผมก็จะย้าย do something ไปจัดการตรง
barSub.stream.listen((msg) {
       //do something
       print('listen: ' + msg.string);
       _barStreamCtrl.add(msg);
});
ก็สามารถใช้งานได้เช่นกันครับ มันยอดไปเลยครับผม

ปล. จากที่ได้ลองเรื่องจัดการให้ครบทุก msg เวลา sub รับ msg เยอะๆ พร้อมๆกัน (มากๆ เกิน 500) เหมือนมัน disconnect sub หรือ unsub ไปเลย แล้วไม่กลับมาเชื่อมต่อ sub ใหม่ด้วยครับ แต่ในความเป็นจริงคงมีเหตุการณ์แบบนี้ยากมากๆที่จะได้รับ sub พร้อมๆ กันเกิน 500 msg ขึ้นไปอ่ะครับ ว่างๆท่านอาจารย์ค่อยดูตรงนี้ให้หน่อยนะครับเผื่ออนาคตมีคนแกล้งยิงเข้ามา แอปฯก็จะ disconnect หมดถ้วนหน้า (ใน _noNatsStreamCtrl ทำงานได้ปกติ) ครับ

**Comment by chartchuo** [comment]
Stream builder น่าจะตั้งใจไม่ส่งมา ทุก event เพราะเป็นส่วนที่เอาไป display เราจัดการเองด้วยวิธีที่ 2 จะดีกว่ามากครับ ส่วนปัญหา เรื่อง disconnected จะรับไปดูต่อนะครับ

**Comment by chartchuo** [comment]
@MisterKon ผม reproduce ไม่ได้ ลองส่งเป็นหมื่นก็ไม่มีการ disconnect ถ้าเป็นไปได้ขอตัวอย่าง code ด้วยครับ

**Comment by MisterKon** [comment]
> @MisterKon ผม reproduce ไม่ได้ ลองส่งเป็นหมื่นก็ไม่มีการ disconnect ถ้าเป็นไปได้ขอตัวอย่าง code ด้วยครับ

- ใน simulator น้อยๆ ผ่านฉลุยครับ แต่ถ้าเยอะๆแบบโดนยิง ก็ร่วงครับ
- run ใน real device iphoneXR และ Samsung Note FAN Edition อาการเหมือนกัน คือ จะรับ msg ได้สักครู่หนึ่ง แล้วก็ค้างไป แต่ยังสามารถกด pub ต่อเนื่องได้ทุกครั้ง nats-server รับได้ครบ แอปฯไม่แฮ้งค์ และยังสามารถสลับไปกดปุ่ม streamControl(ปุ่มล่าง) ได้ปกติครับ
- wifi 4g nats-server local + host ได้ผลคล้ายกันหมด
- ถึงจะ comment บรรทัดนี้ => //await _barStreamCtrl.add(msg); ก็ค้างเหมือนกันครับ
*** หรือเป็นที่ function นี้ => barSub.stream.listen((msg) {} หรือ memory leak หรือแอปฯ สื่อสารกับ nats-server ไม่ทันกำหนดเวลา 2วิ แฮะๆ ผมมาไกลสุดได้แค่นี้หล่ะคับ ><"

Code ที่ทดสอบ ครับ
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:dart_nats/dart_nats.dart' as nats;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State {
  nats.Client natsClient;
  nats.Subscription barSub;
  final _barStreamCtrl = StreamController<nats.Message>();
  final _noNatsStreamCtrl = StreamController();

  void initState() {
    super.initState();
    connect();
  }

  void connect() {
    natsClient = nats.Client();
    natsClient.connect('10.0.2.2');
    barSub = natsClient.sub('bar');
    barSub.stream.listen((msg) async {
      print('listen: ' + msg.string);
      await _barStreamCtrl.add(msg);
    });
  }

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          RaisedButton(
            child: Text('pump data to bar'),
            onPressed: () {
              for (var i = 0; i < 20000; i++) {
//                print('add: $i');
                natsClient.pubString('bar', '$i');
              }
            },
          ),
          Text('StreamBuilder:'),
          StreamBuilder(
            stream: _noNatsStreamCtrl.stream,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                print('snapshot.data: ' + snapshot.data);
              }
              return Text(snapshot.hasData ? snapshot.data : '');
//              yield* streamController.stream;
            },
          ),
          RaisedButton(
            child: Text('pump data to stream อันนี้ทำงานปกติ'),
            onPressed: () {
              for (var i = 0; i < 20000; i++) {
                print('add: $i');
                _noNatsStreamCtrl.add('$i');
              }
            },
          ),
        ],
      ),
    );
  }

  void dispose() {
    natsClient.close();
    super.dispose();
  }
}
// end code

**Comment by chartchuo** [comment]
ผมลองกับ emu แล้วไม่เป็น แต่จะหาทางลองกับ เครื่อง จริงดูอีกทีครับ
https://youtu.be/E1-GowUaFIE

**Comment by chartchuo** [comment]
จะลองแตก isolation เป็นอีก thread เพื่อรับข้อมูลจาก nats server แต่ใช้เวลานิดนึงครับ อาจจะหลายวันหน่อย เสร็จแล้วจะรบกวนขอให้ทดสอบนะครับ

**Comment by chartchuo** [comment]
reproduct ได้แล้ว 
[26607] 2020/01/22 21:10:51.888549 [DBG] 127.0.0.1:39104 - cid:4 - Client Ping Timer
[26607] 2020/01/22 21:10:51.888631 [DBG] 127.0.0.1:39104 - cid:4 - Delaying PING due to client activity 2s ago
[26607] 2020/01/22 21:10:54.797269 [DBG] 127.0.0.1:39104 - cid:4 - Client connection closed

น่าจะเกิดจาก client ทำงานช้าไป server เลยตัด connect จะแก้นี่เรื่องยาวเลยครับ ต้อง optimize หลายอย่าง จะค่อย ๆ ทำไปนะครับ

**Comment by MisterKon** [comment]
> reproduct ได้แล้ว
...
> น่าจะเกิดจาก client ทำงานช้าไป server เลยตัด connect จะแก้นี่เรื่องยาวเลยครับ ต้อง optimize หลายอย่าง จะค่อย ๆ ทำไปนะครับ

สวัสดีครับ ผมว่าเหตุการณ์นี้**ยังไม่เป็นปัญหาและน่าจะไม่เป็นปัญหาใหญ่**นะครับ เนื่องจากผมกำหนดให้ client แต่ละ client sub เข้ามาโดยเป็น unique กันเลย ทำให้หมดสิทธิ์โจมตี client ได้พร้อมกันหลายเครื่อง และการทำงาน Rest API ก็ต้องมีการ pub เข้า sub เดียวกันและเวลาต้องตรงกันมากกว่า 500 pub ถึงจะทำให้ client นั้น dis sub ได้ ซึ่งมันเกิดได้ยากมากๆอยู่แล้วครับ ผมว่า version package ปัจจุบันนี้ก็เพียงพอต่อการใช้งานได้อย่างยอดเยี่ยมแล้วน่ะครับ เดี๋ยวถ้า app chat ผมเสร็จเมื่อไหร่จะมารายงานผลการใช้งานจริงเพื่อทราบอีกครั้งครับผม

แค่นี้ก็ทำให้ระบบ แอปฯ realtime ทำงานแสนจะง่ายกว่าทุกตัว แถมยังฟรีอีกด้วย หาไม่ได้แล้วหล่ะครับ
ขอขอบคุณมากครับ
