### ISSUE TITLE
Does this work with Flutter Web ?

### ISSUE THREAD

**Issue by GreatGreatGreg** [chartchuo/dart-nats#5]
Good job! It works on Android and IOS. Does this work with Flutter Web ? 

Hopefully It supports Flutter Web. Thanks

**Comment by chartchuo** [comment]
NATS protocol require raw TCP which is not available on web. At the moment no plans to support Flutter web.

**Comment by gedw99** [comment]
The nats typescript client can be used and wrapped by dart.

https://github.com/nats-io/nats.js
It supports NATS 2 also

**Comment by chartchuo** [comment]
Thank for information. I just found NATS 2.2 support WebSocket client. I will put into development plan with first priority.

**Comment by gedw99** [comment]
it does

don’t forget about the client side load balancing aspects .

The js lib from nats team probably supports it but I have not checked
